# Generated by Django 5.0.4 on 2024-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='pw',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='*'),
        ),
    ]
