# Generated by Django 5.0.4 on 2024-04-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_email_usuario_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pw',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
