# Generated by Django 5.0.4 on 2024-05-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rol_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='mail',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
