# Generated by Django 5.0.4 on 2024-04-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
        ('usuarios', '0003_alter_usuario_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
