# Generated by Django 5.0.4 on 2024-04-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
