# Generated by Django 5.0.4 on 2024-04-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_rename_nombre_libro_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
