# Generated by Django 5.0.4 on 2024-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_rename_titulo_libro_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
