# Generated by Django 5.0.4 on 2024-05-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_libro_idioma_libro_paginas_alter_libro_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='autor',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='autor',
            name='url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='genero',
            name='url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
    ]
