# Generated by Django 5.0.4 on 2024-05-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
