# Generated by Django 5.0.4 on 2024-06-01 23:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_alter_libro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='modificacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='fecha de modificacion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
