# Generated by Django 5.0.4 on 2024-06-02 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_libro_modificacion_libro_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ('-modificacion',)},
        ),
        migrations.AlterField(
            model_name='libro',
            name='modificacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='fecha de modificacion'),
        ),
    ]
